export CUDA_VISIBLE_DEVICES=3,4
# openlm-research/open_llama_7b_v2
#python main.py --task_namenarraqa --model_name EleutherAI/gpt-j-6B --selective_annotation_method votek --model_cache_dir /local1/fanyin/icl-selective-annotation/models --data_cache_dir /local1/fanyin/icl-selective-annotation/datasets --output_dir outputs/gptj/narraqa/votek
#python main.py --task_name narraqa --model_name facebook/opt-6.7B --selective_annotation_method random --model_cache_dir /local1/fanyin/icl-selective-annotation/models --data_cache_dir /local1/fanyin/icl-selective-annotation/datasets --output_dir outputs/opt-6b/narraqa/random_beam
#python main.py --task_name narraqa --model_name EleutherAI/gpt-j-6B --selective_annotation_method random --prompt_retrieval_method random --model_cache_dir /local1/fanyin/icl-selective-annotation/models --data_cache_dir /local1/fanyin/icl-selective-annotation/datasets --output_dir outputs/gptj/narraqa/random_beam
#python main.py --task_name coqa --semantic_entropy --model_name facebook/opt-6.7B --selective_annotation_method random --prompt_retrieval_method random --seed 44 --model_cache_dir /local2/fanyin/icl-selective-annotation/models --data_cache_dir /local2/fanyin/icl-selective-annotation/datasets --output_dir outputs/opt-6B/coqa/test --temperature 1
# /local2/fanyin/llama-7B
# python main.py --task_name triviaqa --max_in_context_samples 5 --self_check --model_name /local2/fanyin/Llama-2-7b-hf --selective_annotation_method random --prompt_retrieval_method random --seed 44 --model_cache_dir /local2/fanyin/icl-selective-annotation/models --data_cache_dir /local2/fanyin/icl-selective-annotation/datasets --output_dir outputs/llama-2-7b/triviaqa/lid_5000_samples_2 --temperature 0.5
# python main.py --task_name narraqa --max_in_context_samples 0 --self_check --model_name  /local2/fanyin/Llama-2-7b-hf --selective_annotation_method random --prompt_retrieval_method random --seed 44 --model_cache_dir /local2/fanyin/icl-selective-annotation/models --data_cache_dir /local2/fanyin/icl-selective-annotation/datasets --output_dir outputs/llama-2-7b/narraqa/lid_5000_samples --temperature 0.5
# python main.py --task_name triviaqa --max_in_context_samples 2 --semantic_entropy --predictive_entropy --save_files --model_name  /local2/fanyin/Llama-2-7b-hf --selective_annotation_method random --prompt_retrieval_method random --seed 44 --model_cache_dir /local2/fanyin/icl-selective-annotation/models --data_cache_dir /local2/fanyin/icl-selective-annotation/datasets --output_dir outputs/llama-2-7b/triviaqa/lid_5000_samples_2_context --temperature 0.5
# assert(0)
# python main.py --task_name triviaqa --max_in_context_samples 0 --model_name /local2/fanyin/Llama-2-7b-hf --selective_annotation_method random --prompt_retrieval_method random --seed 44 --model_cache_dir /local2/fanyin/icl-selective-annotation/models --data_cache_dir /local2/fanyin/icl-selective-annotation/datasets --output_dir outputs/llama-2-7b/triviaqa/notIT_lid_2000_samples_no_context --temperature 0.5
python main.py --task_name triviaqa --max_in_context_samples 0 --model_name /local2/fanyin/IT_llama2/NIV2Full200 --selective_annotation_method random --prompt_retrieval_method random --seed 44 --model_cache_dir /local2/fanyin/icl-selective-annotation/models --data_cache_dir /local2/fanyin/icl-selective-annotation/datasets --output_dir outputs/llama-2-7b/triviaqa/IT_lid_2000_samples_no_context --temperature 0.5
assert(0)
python main.py --task_name triviaqa --max_in_context_samples 0 --semantic_entropy --predictive_entropy --model_name  /local2/fanyin/Llama-2-13b-hf --selective_annotation_method random --prompt_retrieval_method random --seed 44 --model_cache_dir /local2/fanyin/icl-selective-annotation/models --data_cache_dir /local2/fanyin/icl-selective-annotation/datasets --output_dir outputs/llama-2-13b/triviaqa/lid_5000_samples_no_context --temperature 0.5
python main.py --task_name hotpotqa --max_in_context_samples 0 --semantic_entropy --predictive_entropy  --model_name  /local2/fanyin/Llama-2-13b-hf --selective_annotation_method random --prompt_retrieval_method random --seed 44 --model_cache_dir /local2/fanyin/icl-selective-annotation/models --data_cache_dir /local2/fanyin/icl-selective-annotation/datasets --output_dir outputs/llama-2-13b/hotpotqa/lid_10000_samples_no_context  --temperature 0.5
python main.py --task_name coqa --max_in_context_samples 0  --semantic_entropy --predictive_entropy  --model_name  /local2/fanyin/Llama-2-13b-hf --selective_annotation_method random --prompt_retrieval_method random --seed 44 --model_cache_dir /local2/fanyin/icl-selective-annotation/models --data_cache_dir /local2/fanyin/icl-selective-annotation/datasets --output_dir outputs/llama-2-13b/coqa/lid_5000_samples_bk --temperature 0.5
python main.py --task_name triviaqa --max_in_context_samples 2 --semantic_entropy --predictive_entropy  --model_name  /local2/fanyin/Llama-2-7b-hf --selective_annotation_method random --prompt_retrieval_method random --seed 44 --model_cache_dir /local2/fanyin/icl-selective-annotation/models --data_cache_dir /local2/fanyin/icl-selective-annotation/datasets --output_dir outputs/llama-2-7b/triviaqa/lid_5000_samples_2_context --temperature 0.5
python main.py --task_name hotpotqa --max_in_context_samples 2 --semantic_entropy --predictive_entropy --save_files  --model_name  /local2/fanyin/Llama-2-7b-hf --selective_annotation_method random --prompt_retrieval_method random --seed 44 --model_cache_dir /local2/fanyin/icl-selective-annotation/models --data_cache_dir /local2/fanyin/icl-selective-annotation/datasets --output_dir outputs/llama-2-7b/hotpotqa/lid_10000_samples_2_context  --temperature 1.0
python main.py --task_name triviaqa --max_in_context_samples 2 --semantic_entropy --predictive_entropy --save_files --model_name  /local2/fanyin/Llama-2-13b-hf --selective_annotation_method random --prompt_retrieval_method random --seed 44 --model_cache_dir /local2/fanyin/icl-selective-annotation/models --data_cache_dir /local2/fanyin/icl-selective-annotation/datasets --output_dir outputs/llama-2-13b/triviaqa/lid_5000_samples_2_context --temperature 1.0
python main.py --task_name hotpotqa --max_in_context_samples 2 --semantic_entropy --predictive_entropy --save_files   --model_name  /local2/fanyin/Llama-2-13b-hf --selective_annotation_method random --prompt_retrieval_method random --seed 44 --model_cache_dir /local2/fanyin/icl-selective-annotation/models --data_cache_dir /local2/fanyin/icl-selective-annotation/datasets --output_dir outputs/llama-2-13b/hotpotqa/lid_10000_samples_2_context  --temperature 0.5
assert(0)
# python main.py --task_name hotpotqa --max_in_context_samples 5 --self_check --predictive_entropy --model_name /local2/fanyin/Llama-2-7b-hf --selective_annotation_method random --prompt_retrieval_method random --seed 44 --model_cache_dir /local2/fanyin/icl-selective-annotation/models --data_cache_dir /local2/fanyin/icl-selective-annotation/datasets --output_dir outputs/llama-2-7b/hotpotqa/lid_3000_samples --only_do_generation --temperature 1.0
python main.py --task_name triviaqa --max_in_context_samples 5 --self_check --semantic_entropy --predictive_entropy --model_name /local2/fanyin/Llama-2-7b-hf --selective_annotation_method random --prompt_retrieval_method random --seed 44 --model_cache_dir /local2/fanyin/icl-selective-annotation/models --data_cache_dir /local2/fanyin/icl-selective-annotation/datasets --output_dir outputs/llama-2-7b/triviaqa/lid_5000_samples_2_greedy --temperature 0.5
python main.py --task_name narraqa --max_in_context_samples 0 --self_check --predictive_entropy --model_name  /local2/fanyin/Llama-2-7b-hf --selective_annotation_method random --prompt_retrieval_method random --seed 44 --model_cache_dir /local2/fanyin/icl-selective-annotation/models --data_cache_dir /local2/fanyin/icl-selective-annotation/datasets --output_dir outputs/llama-2-7b/narraqa/lid_5000_samples_greedy --temperature 0.5
python main.py --task_name coqa --max_in_context_samples 0 --self_check --predictive_entropy --model_name  /local2/fanyin/Llama-2-7b-hf --selective_annotation_method random --prompt_retrieval_method random --seed 44 --model_cache_dir /local2/fanyin/icl-selective-annotation/models --data_cache_dir /local2/fanyin/icl-selective-annotation/datasets --output_dir outputs/llama-2-7b/coqa/lid_5000_samples_greedy --temperature 0.5
assert(0)
python main.py --task_name triviaqa --self_check --predictive_entropy --model_name openlm-research/open_llama_3b_v2 --selective_annotation_method random --prompt_retrieval_method random --seed 44 --model_cache_dir /local2/fanyin/icl-selective-annotation/models --data_cache_dir /local2/fanyin/icl-selective-annotation/datasets --output_dir outputs/openllama-3b/triviaqa/lid_3000_samples --only_do_generation --temperature 0.5
python main.py --task_name narraqa --max_in_context_samples 0 --self_check --predictive_entropy --model_name  openlm-research/open_llama_3b_v2 --selective_annotation_method random --prompt_retrieval_method random --seed 44 --model_cache_dir /local2/fanyin/icl-selective-annotation/models --data_cache_dir /local2/fanyin/icl-selective-annotation/datasets --output_dir outputs/openllama-3b/narraqa/lid_3000_samples --only_do_generation --temperature 0.5
python main.py --task_name coqa --max_in_context_samples 0 --self_check --predictive_entropy --model_name  openlm-research/open_llama_3b_v2 --selective_annotation_method random --prompt_retrieval_method random --seed 44 --model_cache_dir /local2/fanyin/icl-selective-annotation/models --data_cache_dir /local2/fanyin/icl-selective-annotation/datasets --output_dir outputs/openllama-3b/coqa/lid_3000_samples --only_do_generation --temperature 0.5
exit(0)

python main.py --task_name xsum --model_name facebook/opt-6.7B --selective_annotation_method random --prompt_retrieval_method random --model_cache_dir /local1/fanyin/icl-selective-annotation/models --data_cache_dir /local1/fanyin/icl-selective-annotation/datasets --output_dir outputs/opt-6b/xsum/random
python main.py --task_name xsum --model_name facebook/opt-6.7B --selective_annotation_method votek --model_cache_dir /local1/fanyin/icl-selective-annotation/models --data_cache_dir /local1/fanyin/icl-selective-annotation/datasets --output_dir outputs/opt-6b/xsum/votek

python main.py --task_name xsum --model_name EleutherAI/gpt-j-6B --selective_annotation_method random --model_cache_dir /local1/fanyin/icl-selective-annotation/models --data_cache_dir /local1/fanyin/icl-selective-annotation/datasets --output_dir outputs/gptj/xsum/similar
python main.py --task_name xsum --model_name EleutherAI/gpt-j-6B --selective_annotation_method votek --model_cache_dir /local1/fanyin/icl-selective-annotation/models --data_cache_dir /local1/fanyin/icl-selective-annotation/datasets --output_dir outputs/gptj/xsum/votek
python main.py --task_name xsum --model_name EleutherAI/gpt-j-6B --selective_annotation_method random --prompt_retrieval_method random --model_cache_dir /local1/fanyin/icl-selective-annotation/models --data_cache_dir /local1/fanyin/icl-selective-annotation/datasets --output_dir outputs/gptj/xsum/random

python main.py --task_name narraqa --model_name facebook/opt-6.7B --selective_annotation_method votek --model_cache_dir /local1/fanyin/icl-selective-annotation/models --data_cache_dir /local1/fanyin/icl-selective-annotation/datasets --output_dir outputs/opt-6b/narraqa/votek
python main.py --task_name narraqa --model_name facebook/opt-6.7B --selective_annotation_method random --prompt_retrieval_method random --model_cache_dir /local1/fanyin/icl-selective-annotation/models --data_cache_dir /local1/fanyin/icl-selective-annotation/datasets --output_dir outputs/opt-6b/narraqa/random
python main.py --task_name narraqa --model_name facebook/opt-6.7B --selective_annotation_method random --model_cache_dir /local1/fanyin/icl-selective-annotation/models --data_cache_dir /local1/fanyin/icl-selective-annotation/datasets --output_dir outputs/opt-6b/narraqa/similar

python main.py --task_name narraqa --model_name EleutherAI/gpt-j-6B --selective_annotation_method votek --model_cache_dir /local1/fanyin/icl-selective-annotation/models --data_cache_dir /local1/fanyin/icl-selective-annotation/datasets --output_dir outputs/gptj/narraqa/votek
python main.py --task_name narraqa --model_name EleutherAI/gpt-j-6B --selective_annotation_method random --prompt_retrieval_method random --model_cache_dir /local1/fanyin/icl-selective-annotation/models --data_cache_dir /local1/fanyin/icl-selective-annotation/datasets --output_dir outputs/gptj/narraqa/random
python main.py --task_name narraqa --model_name EleutherAI/gpt-j-6B --selective_annotation_method random --model_cache_dir /local1/fanyin/icl-selective-annotation/models --data_cache_dir /local1/fanyin/icl-selective-annotation/datasets --output_dir outputs/gptj/narraqa/similar


